export const FETCH_BANNERS_START = 'FETCH_BANNERS_START ';
export const FETCH_BANNERS_SUCCESS = 'FETCH_BANNERS_SUCCESS ';
export const FETCH_BANNERS_FAIL = 'FETCH_BANNERS_FAIL ';

export const FETCH_SONGOH_SHALTGAAN_GARCHIG_START = 'FETCH_SONGOH_SHALTGAAN_GARCHIG_START ';
export const FETCH_SONGOH_SHALTGAAN_GARCHIG_SUCCESS = 'FETCH_SONGOH_SHALTGAAN_GARCHIG_SUCCESS ';
export const FETCH_SONGOH_SHALTGAAN_GARCHIG_FAIL = 'FETCH_SONGOH_SHALTGAAN_GARCHIG_FAIL ';